# 重新审视Iris数据集


In [118]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import numpy as np
from torch.optim import Adam

In [119]:
iris_data = load_iris(return_X_y=True)
# print(iris_data)
# print(type(iris_data))
print(type(iris_data[0])) # features input_data
print('*' * 100)
print(iris_data[1])

<class 'numpy.ndarray'>
****************************************************************************************************
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [120]:
print(iris_data[0].shape) # ->[N, Feature_num]

(150, 4)


In [121]:
class IrisDataset(Dataset):

    def __init__(self, X:np.ndarray, y:np.ndarray):
        super(IrisDataset, self).__init__()
        X = X.astype('float32')
        y = y.astype('int64')
        self.X = torch.from_numpy(X)
        self.y = torch.from_numpy(y)

    '''
    ->datas, labels
    '''
    def __getitem__(self, index):
        return X[index], y[index]

    def __len__(self)->int:
        return len(X)

In [122]:
X = iris_data[0]
y = iris_data[1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True)
print(X_train)
print(X_trian.shape)

[[4.9 3.  1.4 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.6 1.4 0.1]
 [4.8 3.  1.4 0.1]
 [4.6 3.1 1.5 0.2]
 [6.3 2.8 5.1 1.5]
 [6.  2.2 5.  1.5]
 [6.7 3.1 4.4 1.4]
 [5.7 2.9 4.2 1.3]
 [6.4 2.7 5.3 1.9]
 [5.5 4.2 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [6.  3.  4.8 1.8]
 [6.9 3.1 4.9 1.5]
 [4.7 3.2 1.3 0.2]
 [5.1 3.7 1.5 0.4]
 [6.5 3.  5.8 2.2]
 [6.9 3.1 5.4 2.1]
 [5.1 3.5 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.5 2.6 4.4 1.2]
 [5.8 2.7 4.1 1. ]
 [5.  3.5 1.6 0.6]
 [5.8 2.7 3.9 1.2]
 [7.7 2.8 6.7 2. ]
 [5.5 3.5 1.3 0.2]
 [7.1 3.  5.9 2.1]
 [6.  2.2 4.  1. ]
 [6.5 3.  5.2 2. ]
 [5.9 3.2 4.8 1.8]
 [5.8 2.6 4.  1.2]
 [4.7 3.2 1.6 0.2]
 [5.  2.  3.5 1. ]
 [5.7 2.6 3.5 1. ]
 [6.  2.9 4.5 1.5]
 [5.1 2.5 3.  1.1]
 [6.4 2.8 5.6 2.1]
 [5.9 3.  5.1 1.8]
 [5.6 2.7 4.2 1.3]
 [4.8 3.1 1.6 0.2]
 [5.6 2.8 4.9 2. ]
 [5.  3.6 1.4 0.2]
 [6.3 3.3 6.  2.5]
 [6.4 3.1 5.5 1.8]
 [5.6 3.  4.1 1.3]
 [5.5 2.4 3.7 1. ]
 [6.1 2.9 4.7 1.4]
 [5.7 3.8 1.7 0.3]
 [7.9 3.8 6.4 2. ]
 [5.7 2.8 4.5 1.3]
 [6.2 2.2 4.5 1.5]
 [6.4 3.2 5.3 2.3]
 [5.4 3.9 1.

In [127]:
Iris_train_data = IrisDataset(X=X_train, y=y_train)
Iris_test_data = IrisDataset(X=X_test,y=y_test)
print(Iris_train_data)

pydev debugger: Unable to find real location for: /var/folders/4q/mxhf2gj12ll_msd5l7shm0dw0000gn/T/ipykernel_37220/2285690496.py


In [124]:
class Network(nn.Module):
    def __init__(self, feature_num, layer_num, output_num):
        super(Network, self).__init__()
        self.classifier = nn.Sequential()
        layer_num = layer_num
        feature_num = feature_num
        out = feature_num * 4
        for index in range(layer_num - 1):
            self.classifier.add_module(f"Linear{index}", nn.Linear(feature_num, out))
            feature_num = out
            out *= 2
            self.classifier.add_module(f"Relu{index}", nn.ReLU())
        self.classifier.add_module(f'Linear{layer_num - 1}', nn.Linear(feature_num, output_num))
        self.classifier.add_module(f"Relu{layer_num - 1}", nn.ReLU())

    def forward(self, x):
        return self.classifier(x)




In [125]:
net = Network(4,6, 3)
print(net)
opt = Adam(lr=1e-3, params=net.parameters())

Network(
  (classifier): Sequential(
    (Linear0): Linear(in_features=4, out_features=16, bias=True)
    (Relu0): ReLU()
    (Linear1): Linear(in_features=16, out_features=32, bias=True)
    (Relu1): ReLU()
    (Linear2): Linear(in_features=32, out_features=64, bias=True)
    (Relu2): ReLU()
    (Linear3): Linear(in_features=64, out_features=128, bias=True)
    (Relu3): ReLU()
    (Linear4): Linear(in_features=128, out_features=256, bias=True)
    (Relu4): ReLU()
    (Linear5): Linear(in_features=256, out_features=3, bias=True)
    (Relu5): ReLU()
  )
)


In [141]:
# To Do:将训练代码包装成训练方法 def train():

net.train()
train_dataloader = DataLoader(Iris_train_data, shuffle=True, batch_size=20)
loss_fn = nn.CrossEntropyLoss()

EPOCH = 100
for epoch in range(EPOCH):
    for batch_id, (input_datas, labels) in enumerate(train_dataloader): # batch_id, data / X, label / y
        input_datas = torch.tensor(input_datas, dtype=torch.float32)
        pred = net(input_datas)
        loss = loss_fn(pred, labels)

        opt.zero_grad()
        loss.backward()
        opt.step()
        print(f"epoch:{epoch}, batch_id:{batch_id}, loss:{loss}")



/var/folders/4q/mxhf2gj12ll_msd5l7shm0dw0000gn/T/ipykernel_37220/4032065394.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input_datas = torch.tensor(input_datas, dtype=torch.float32)


epoch:0, batch_id:0, loss:0.40908655524253845
epoch:0, batch_id:1, loss:0.48439350724220276
epoch:0, batch_id:2, loss:0.5057466626167297
epoch:0, batch_id:3, loss:0.4764196276664734
epoch:0, batch_id:4, loss:0.5469417572021484
epoch:0, batch_id:5, loss:0.08985585719347
epoch:0, batch_id:6, loss:0.4395938813686371
epoch:0, batch_id:7, loss:0.33074474334716797
epoch:1, batch_id:0, loss:0.41475898027420044
epoch:1, batch_id:1, loss:0.22079579532146454
epoch:1, batch_id:2, loss:0.3952319025993347
epoch:1, batch_id:3, loss:0.3532574474811554
epoch:1, batch_id:4, loss:0.48600825667381287
epoch:1, batch_id:5, loss:0.5711844563484192
epoch:1, batch_id:6, loss:0.5949288606643677
epoch:1, batch_id:7, loss:0.0017483517294749618
epoch:2, batch_id:0, loss:0.38970497250556946
epoch:2, batch_id:1, loss:0.17439736425876617
epoch:2, batch_id:2, loss:0.231878399848938
epoch:2, batch_id:3, loss:0.4234147071838379
epoch:2, batch_id:4, loss:0.3567884564399719
epoch:2, batch_id:5, loss:0.3404872417449951
ep